server:
  port: 8084
  
  

  
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url.defaultZone: http://localhost:8761/eureka
    

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
        - Path=/users/**
        
      - id: HOTEL-SERVICE
        uri: lb://HOTEL-SERVICE
        predicates:
        - Path=/hotel/**,/staff/**
        
      - id: RATING-SERVICE
        uri: lb://RATING-SERVICE
        predicates:
        - Path=/rating/**
        
#Remove This configuration if you do not want secutiry OKTA    
okta:
  oauth2:
    issuer: https://dev-16884742.okta.com/oauth2/default
    audience: api://default
    client-id: 0oab4dirc4A6qIGOE5d7
    client-secret: -hOl3iVCRMRazC12-H8v8wQlabJw_-3xaeZLgHYUtfeqWdCUPx8Sdw1fG2PyZK_H
    scopes: openid, profile, email, offline_access
        
    